import { ReactNode } from "react";
import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";

const kadwa = localFont({
  src: [
    {
      path: '../public/fonts/Kadwa-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Kadwa-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: "--font-kadwa",
});

export const metadata: Metadata = {
  title: "Vet Plus Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full flex flex-col">
      <body className={`${kadwa.className} antialiased h-full min-h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <main className="h-full w-full p-6">
              {children}
            </main>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
