import { AnimalsType } from "@/lib/tempType";
import { AnimalGender, AnimalStatus } from "@/lib/enums";
import RootPage from "@/components/RootPage";
import HeaderPage from "../components/shared/HeaderPage";
import { PawPrint } from "lucide-react";

export default async function Home() {
  const animals: AnimalsType[] = [
    {
      id: "1",
      ear_tag: "BR001",
      breed: "Holandesa",
      name: "Estrela",
      description: "Vaca leiteira saudável e dócil.",
      birth_date: "2020-03-15",
      weight: 520.4,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.LACTATING,
    },
    {
      id: "2",
      ear_tag: "BR002",
      breed: "Holandesa",
      name: "Trovão",
      description: "Touro de excelente genética.",
      birth_date: "2019-07-08",
      weight: 780.2,
      gender: AnimalGender.MALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "3",
      ear_tag: "BR003",
      breed: "Holandesa",
      name: "Aurora",
      description: "Fêmea prenha com histórico de boa produção.",
      birth_date: "2021-01-21",
      weight: 480.0,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.PREGNANT,
    },
    {
      id: "4",
      ear_tag: "BR004",
      breed: "Holandesa",
      name: "Nuvem",
      description: "Bezerra jovem, dócil e ativa.",
      birth_date: "2023-05-11",
      weight: 210.5,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "5",
      ear_tag: "BR005",
      breed: "Holandesa",
      name: "Relâmpago",
      description: "Macho forte destinado à reprodução.",
      birth_date: "2020-09-29",
      weight: 740.7,
      gender: AnimalGender.MALE,
      status: AnimalStatus.INSEMINATED,
    },
    {
      id: "6",
      ear_tag: "BR006",
      breed: "Holandesa",
      name: "Luna",
      description: "Produz leite de alta qualidade.",
      birth_date: "2021-04-05",
      weight: 495.3,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.LACTATING,
    },
    {
      id: "7",
      ear_tag: "BR007",
      breed: "Holandesa",
      name: "Sol",
      description: "Animal tranquilo, ideal para cruzamento.",
      birth_date: "2018-02-14",
      weight: 680.1,
      gender: AnimalGender.MALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "8",
      ear_tag: "BR008",
      breed: "Holandesa",
      name: "Esperança",
      description: "Fêmea prenha com boa linhagem leiteira.",
      birth_date: "2021-08-10",
      weight: 505.6,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.PREGNANT,
    },
    {
      id: "9",
      ear_tag: "BR009",
      breed: "Holandesa",
      name: "Valente",
      description: "Touro vigoroso, excelente para monta natural.",
      birth_date: "2019-12-02",
      weight: 790.9,
      gender: AnimalGender.MALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "10",
      ear_tag: "BR010",
      breed: "Holandesa",
      name: "Serena",
      description: "Fêmea calma e de boa saúde.",
      birth_date: "2022-06-19",
      weight: 360.8,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "11",
      ear_tag: "BR011",
      breed: "Holandesa",
      name: "Bento",
      description: "Animal usado em programas genéticos.",
      birth_date: "2018-10-25",
      weight: 755.0,
      gender: AnimalGender.MALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "12",
      ear_tag: "BR012",
      breed: "Holandesa",
      name: "Lua",
      description: "Fêmea inseminada recentemente.",
      birth_date: "2021-11-03",
      weight: 475.2,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.INSEMINATED,
    },
    {
      id: "13",
      ear_tag: "BR013",
      breed: "Holandesa",
      name: "Brilho",
      description: "Bezerra ativa e saudável.",
      birth_date: "2023-03-22",
      weight: 190.3,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "14",
      ear_tag: "BR014",
      breed: "Holandesa",
      name: "Atlas",
      description: "Touro de grande porte.",
      birth_date: "2019-01-10",
      weight: 810.5,
      gender: AnimalGender.MALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "15",
      ear_tag: "BR015",
      breed: "Holandesa",
      name: "Flor",
      description: "Fêmea prenha com bom histórico produtivo.",
      birth_date: "2020-05-06",
      weight: 500.1,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.PREGNANT,
    },
    {
      id: "16",
      ear_tag: "BR016",
      breed: "Holandesa",
      name: "Céu",
      description: "Bezerro calmo e sociável.",
      birth_date: "2023-07-01",
      weight: 200.0,
      gender: AnimalGender.MALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "17",
      ear_tag: "BR017",
      breed: "Holandesa",
      name: "Luz",
      description: "Vaca leiteira com boa produtividade.",
      birth_date: "2020-08-14",
      weight: 520.9,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.LACTATING,
    },
    {
      id: "18",
      ear_tag: "BR018",
      breed: "Holandesa",
      name: "Força",
      description: "Animal macho em fim de ciclo produtivo.",
      birth_date: "2016-04-22",
      weight: 845.0,
      gender: AnimalGender.MALE,
      status: AnimalStatus.END_OF_LIFE,
    },
    {
      id: "19",
      ear_tag: "BR019",
      breed: "Holandesa",
      name: "Branca",
      description: "Vaca inseminada recentemente.",
      birth_date: "2021-09-09",
      weight: 490.2,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.INSEMINATED,
    },
    {
      id: "20",
      ear_tag: "BR020",
      breed: "Holandesa",
      name: "Cristal",
      description: "Fêmea jovem e saudável.",
      birth_date: "2022-01-19",
      weight: 345.6,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "21",
      ear_tag: "BR021",
      breed: "Holandesa",
      name: "Rosa",
      description: "Fêmea prenha e tranquila.",
      birth_date: "2021-02-25",
      weight: 480.9,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.PREGNANT,
    },
    {
      id: "22",
      ear_tag: "BR022",
      breed: "Holandesa",
      name: "Falcão",
      description: "Macho forte e ativo.",
      birth_date: "2019-10-10",
      weight: 760.3,
      gender: AnimalGender.MALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "23",
      ear_tag: "BR023",
      breed: "Holandesa",
      name: "Margarida",
      description: "Fêmea de alta produção leiteira.",
      birth_date: "2020-07-13",
      weight: 505.7,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.LACTATING,
    },
    {
      id: "24",
      ear_tag: "BR024",
      breed: "Holandesa",
      name: "Leão",
      description: "Animal experiente em reprodução.",
      birth_date: "2018-09-04",
      weight: 800.0,
      gender: AnimalGender.MALE,
      status: AnimalStatus.AVAILABLE,
    },
    {
      id: "25",
      ear_tag: "BR025",
      breed: "Holandesa",
      name: "Neve",
      description: "Bezerra curiosa e saudável.",
      birth_date: "2023-04-18",
      weight: 215.5,
      gender: AnimalGender.FEMALE,
      status: AnimalStatus.AVAILABLE,
    },
  ];

  return (
    <>
      <HeaderPage title="Animals List" icon={PawPrint} />
      <RootPage animals={animals} />
    </>
  );
}
